#!/bin/sh

# Check if package manager is known
if [ -z ${PKG_PACKAGE_MANAGER} ]; then
    echo "PKG_PACKAGE_MANAGER is not set. Please set it accordingly!"
    exit 0
fi

method_not_supported() {
        echo "method not supported for ${PKG_PACKAGE_MANAGER}"
        exit 1
}

print_help() {
    echo "Usage: pkg ACTION|WRAPPER [PKGNAME|FILE]\n"
    echo "ACTIONS:"
    echo " help           print this help message."
    echo " install        install package with PKGNAME."
    echo " remove         remove package with PKGNAME."
    echo " search         search for PKGNAME in name/description."
    echo " upgrade        upgrade PKGNAME or all packages."
    echo " list           list all installed packages."
    echo " info           show information for package PKGNAME."
    echo " which          check to which package FILE belongs."
    echo " files          list files contained in package PKGNAME."
    echo " clean          remove obsolete packages from package cache."
    echo " hold           hold package with PKGNAME."
    echo " unhold         unhold package with PKGNAME."
    echo " deps           list dependencies for package PKGNAME"
    echo " revdeps        list packages which need package PKGNAME."
    echo " orphans        list orphaned packages."
    echo " "
    echo "WRAPPERS:"
    echo " db             calls xbps-pkgdb."
    echo " alternatives   calls xbps-alternatives."
    echo " query          calls xbps-query."
    echo " reconfigure    calls xbps-reconfigure."
    echo " rindex         calls xbps-rindex."
}

if [ $# -lt 1 ]; then
    print_help
    exit 0
fi


case "$PKG_PACKAGE_MANAGER" in
    apt|dpkg)
        ;;
    yaourt)
        install_cmd="yaourt -S"
        remove_cmd="yaourt -R"
        search_cmd="yaourt -Ss"
        upgrade_cmd="yaourt -Syu"
        update_cmd="yaourt -Syy"
        list_cmd="yaourt -Qqe"
        info_cmd="yaourt -Qi"
        which_cmd="yaourt -Qo"
        files_cmd="yaourt -Ql"
        clean_cmd="yaourt -Scc"
        hold_cmd="method_not_supported"
        unhold_cmd="method_not_supported "
        deps_cmd="yaourt -Sq --depends"
        revdeps_cmd="yaourt -Qi"
        orphans_cmd="yaourt -Qtd"
        ;;
    pacman)
        ;;
    xbps)
        install_cmd="xbps-install -S"
        remove_cmd="xbps-remove"
        search_cmd="xbps-query -Rs"
        upgrade_cmd="xbps-install -Su"
        update_cmd="xbps-install -S"
        list_cmd="xbps-query -l"
        info_cmd="xbps-query"
        which_cmd="xbps-query -o"
        files_cmd="xbps-query -f"
        clean_cmd="xbps-remove -O"
        hold_cmd="xbps-pkgdb -m hold"
        unhold_cmd="xbps-pkgdb -m unhold"
        deps_cmd="xbps-query -Rx"
        revdeps_cmd="xbps-query -RX"
        orphans_cmd="xbps-query -O"
        ;;
esac

METHOD=$1
shift

case "$METHOD" in
    help)
        print_help
        ;;
    install)
        $install_cmd "$@"
        ;;
    remove)
        $remove_cmd "$@"
        ;;
    search)
        $search_cmd "$@"
        ;;
    update)
        $update_cmd "$@"
        ;;
    upgrade)
        $upgrade_cmd "$@"
        ;;
    list)
        $list_cmd "$@"
        ;;
    info)
        $info_cmd "$@"
        ;;
    which)
        $which_cmd "$@"
        ;;
    files)
        $files_cmd "$@"
        ;;
    clean)
        $clean_cmd "$@"
        ;;
    hold)
        $hold_cmd "$@"
        ;;
    unhold)
        $unhold_cmd "$@"
        ;;
    deps|dependencies|depends-on)
        $deps_cmd "$@"
        ;;
    revdeps|reverse-dependencies|required-by)
        $revdeps_cmd "$@"
        ;;
    orphans)
        $orphans_cmd "$@"
        ;;
#    db)
#        shift; xbps-pkgdb "$@"
#        ;;
#    alternatives)
#        shift; xbps-alternatives "$@"
#        ;;
#    query)
#        shift; xbps-query "$@"
#        ;;
#    reconfigure)
#        shift; xbps-reconfigure "$@"
#        ;;
#    rindex)
#        shift; xbps-rindex "$@"
#        ;;
    *)
        echo "Unknown option: $*"
        print_help
        ;;
esac

